build-job:
  stage: build
  script:
    - env 

test-job1:
  stage: test
  script:
    - env

test-job2:
  stage: test
  script:
    - env 

deploy-prod:
  stage: deploy
  script:
    - env
  environment: production
