build-gradle-project:
  image: eclipse-temurin:latest

  script:
    - echo "Lets have a look at the environment"
    - uname -a
    - cat /etc/*release*
    - java --version
    - ./gradlew --version
    - env
    - ./gradlew build

  artifacts:
    reports:
      junit: '**/build/test-results/**/TEST-*.xml'
