image: gradle:alpine

stages:
  - build
  - test

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
      - .gradle/wrapper

build:
  stage: build
  script: gradle --build-cache assemble

test:
  stage: test
  script: gradle test
  artifacts:
    when: always
    reports:
      junit: '**/build/test-results/**/TEST-*.xml'

