image: gradle:alpine

stages:
  - build
  - test

cache:
  key:
    files:
      - gradle/wrapper/gradle-wrapper.properties
  paths:
      - .gradle/wrapper

build:
  stage: build
  script: gradle --build-cache assemble

test:
  stage: test
  script: gradle check
