build-gradle-project:
  image: gradle:jdk21-jammy

  script:
    - gradle wrapper
    - ./gradlew test

  artifacts:
    reports:
      paths: build/test/results/test
      junit: TEST-*.xml

  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

  cache:
    paths:
      - .gradle/wrapper
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties

