spring:
  application:
    name: spring-academy-restful-lab
  # We are using hsqldb in server mode, so we need to tell spring to explicitly run the init scripts
  # See https://docs.spring.io/spring-boot/how-to/data-initialization.html
  sql:
    init:
      schema-locations: 'classpath:/devdb/schema.sql'
      data-locations: 'classpath:/devdb/data.sql'
      mode: always
  # Show the sql and pretty print
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/authz.pub

# I want to see in the console the database connection pool properties
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.security: TRACE

# Custom database properties
app:
  datasource:
    jdbc-url: 'jdbc:hsqldb:hsql://localhost/rewards'
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    username: sa
