spring:
  application:
    name: spring-academy-restful-lab
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  # We are using hsqldb in server mode, so we need to tell spring to explicitly run the init scripts
  # See https://docs.spring.io/spring-boot/how-to/data-initialization.html
  app:
    datasource:
      jdbc-url: 'jdbc:hsqldb:hsql://localhost/rewards'
      username: sa
  sql:
    init:
      schema-locations: 'classpath:/devdb/schema.sql'
      data-locations: 'classpath:/devdb/data.sql'
      mode: always
  # Show the sql and pretty print
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/authz.pub
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.security: TRACE

---
spring:
  config:
    activate:
      on-profile: test
  # We are using hsqldb in server mode, so we need to tell spring to explicitly run the init scripts
  # See https://docs.spring.io/spring-boot/how-to/data-initialization.html
  datasource:
    url: 'jdbc:mysql://localhost:3306/rewards'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${REWARDS_TEST_DB_USERNAME}
    password: ${REWARDS_TEST_DB_PASSWORD}
  sql:
    init:
      schema-locations: 'classpath:/testdb/mysql_schema.sql'
      data-locations: 'classpath:/testdb/mysql_data.sql'
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-3luybo0t8652zavi.us.auth0.com/
          jwk-set-uri: https://dev-3luybo0t8652zavi.us.auth0.com/.well-known/jwks.json
          audiences: https://api.rewards.com
logging:
  level:
    org.springframework.security: TRACE