scrape_configs:
  - job_name: 'spring-boot-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['localhost:8080']
    oauth2:
      token_url: 'https://dev-3luybo0t8652zavi.us.auth0.com/oauth/token'
      client_id: PROMETHEUS_REWARDS_API_CLIENT_ID
      client_secret: PROMETHEUS_REWARDS_API_CLIENT_SECRET
      endpoint_params:
        audience: 'https://api.rewards.com'