name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false

    - name: Create the gradle wrapper
      run: gradle --scan wrapper

    - name: Build (no tests)
      run: ./gradlew --build-cache assemble

    - name: Test
      run: ./gradlew --build-cache test

    - name: Analyze code
      env:
        GITHUB_TOKEN: ${{ secrets.SONAR_GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew --build-cache sonar

    - name: Archive code coverage results (jacoco)
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: build/reports/jacoco/test/jacocoTestReport.xml

    - name: Archive unit tests reports
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-reports
        path: build/test-results/**/TEST-*.xml

